from pathlib import Path
from html import escape
R=Path(__file__).resolve().parents[1]
VERSION='scout-20260905b'
NAV=[('index.html','Возможности'),('scout.html','Как начать'),('model.html','Кого искать'),('payments.html','Выплаты')]
def button(text,href,kind='primary'):
    return f'<a class="button {kind}" href="{href}">{text}<span aria-hidden="true">↗</span></a>'
def header(page):
    links=''.join(f'<a href="/{p}"'+(' aria-current="page"' if p==page else '')+f'>{t}</a>' for p,t in NAV)
    return f'''<a class="skip" href="#main">К содержанию</a><header class="header"><div class="wrap header-inner"><a class="brand" href="/" aria-label="SCAUTDOM, главная">scautdom<span aria-hidden="true">+</span></a><nav class="desktop-nav" aria-label="Основная навигация">{links}</nav><a class="header-cta" href="/scout.html#apply">Стать скаутом <span aria-hidden="true">↗</span></a><details class="mobile-nav"><summary>Меню</summary><nav aria-label="Мобильная навигация">{links}<a href="/scout.html#apply">Стать скаутом</a></nav></details></div></header>'''
def footer():
    return '''<footer class="footer"><div class="wrap"><div class="footer-top"><div><a class="brand" href="/">scautdom<span aria-hidden="true">+</span></a><p>Твой круг общения.<br>Новые возможности.</p></div><nav aria-label="Внизу страницы"><a href="/scout.html">Стать скаутом</a><a href="/model.html">Условия моделей</a><a href="/payments.html">Выплаты и VIP</a><a href="/privacy.html">Конфиденциальность</a></nav><div><span class="eyebrow">Начнём знакомство</span><a class="footer-contact" href="/scout.html#apply">Расскажи о своём плане ↗</a><p>Общение с командой — в Telegram.</p></div></div><div class="footer-bottom"><span>© 2026 SCAUTDOM · Участники 18+</span><span>Партнёрская программа в сфере вебкам. Не официальный сайт Chaturbate.</span></div></div></footer><div class="mobile-bar"><span>Твой старт в скаутинге</span><a href="/scout.html#apply">Начать ↗</a></div>'''
def write(page,title,desc,body):
    path='/' if page=='index.html' else '/'+page
    text=f'''<!doctype html><html lang="ru"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><meta name="theme-color" content="#f8f9fc"><meta name="referrer" content="strict-origin-when-cross-origin"><title>{escape(title)}</title><meta name="description" content="{escape(desc,quote=True)}"><link rel="canonical" href="https://www.scautdom.com{path}"><meta property="og:type" content="website"><meta property="og:locale" content="ru_RU"><meta property="og:site_name" content="SCAUTDOM"><meta property="og:title" content="{escape(title,quote=True)}"><meta property="og:description" content="{escape(desc,quote=True)}"><meta property="og:url" content="https://www.scautdom.com{path}"><link rel="icon" href="/assets/favicon.svg" type="image/svg+xml"><link rel="stylesheet" href="/assets/site.css?v={VERSION}"><script src="/assets/lead-core.js?v={VERSION}" defer></script><script src="/assets/site.js?v={VERSION}" defer></script></head><body data-release="{VERSION}">{header(page)}<main id="main">{body}</main>{footer()}</body></html>'''
    (R/page).write_text(text)
def heading(label,title,desc=''):
    return f'<div class="section-head"><div><span class="eyebrow">{label}</span><h2>{title}</h2></div>'+ (f'<p>{desc}</p>' if desc else '')+'</div>'
def faqs(items):
    return '<div class="faq">'+''.join(f'<details><summary>{q}<span aria-hidden="true">+</span></summary><div class="answer">{a}</div></details>' for q,a in items)+'</div>'
def cta():
    return '<section class="wrap section"><div class="cta-panel"><div><span class="eyebrow">От интереса — к действию</span><h2>Начни с одного<br>хорошего знакомства.</h2><p>Расскажи, где планируешь искать моделей.<br>Это станет отправной точкой разговора с командой.</p></div>'+button('Обсудить мой старт','/scout.html#apply','white')+'</div></section>'
def timeline():
    return '''<ol class="timeline"><li><span class="step-no">01</span><div><span class="eyebrow">Твоя часть</span><h3>Найти и заинтересовать</h3><p>Знакомишься с программой, находишь подходящую взрослую девушку и объясняешь предложение.</p></div></li><li><span class="step-no">02</span><div><span class="eyebrow">Вместе</span><h3>Познакомить с командой</h3><p>Уточняешь готовность к работе. С её согласия передаёшь информацию нам. Мы проводим отбор.</p></div></li><li><span class="step-no">03</span><div><span class="eyebrow">Наша часть</span><h3>Обучить и запустить</h3><p>Помогаем модели с оборудованием, аккаунтом, обучением, продвижением и рабочим процессом.</p></div></li><li><span class="step-no">04</span><div><span class="eyebrow">Твой результат</span><h3>Получать вознаграждение</h3><p>До $3 000 за модель за три полных месяца по условиям программы. Дальше можно развивать свою сеть.</p></div></li></ol>'''
def calculator():
    return '''<div class="calculator" data-scout-calculator><div class="calc-controls"><span class="eyebrow">Пример для твоей цели</span><h3>Сколько моделей<br>ты хочешь привлечь?</h3><div class="range-heading"><label for="model-count">Завершили первые 3 месяца</label><output id="model-count-label" for="model-count">3</output></div><input id="model-count" type="range" min="1" max="10" step="1" value="3" aria-describedby="calc-note"><div class="range-labels"><span>1 модель</span><span>10 моделей</span></div><p id="calc-note" class="small">Расчёт предполагает одобрение каждой модели, выполнение рабочего плана и завершение всех трёх месяцев. Это пример, а не прогноз заработка.</p></div><div class="calc-result"><span class="eyebrow">Всего за 3 полных месяца</span><output class="calc-total" data-total aria-live="polite">$9 000</output><div class="calc-months"><div><span>1-й месяц</span><strong data-month>$3 000</strong></div><div><span>2-й месяц</span><strong data-month>$3 000</strong></div><div><span>3-й месяц</span><strong data-month>$3 000</strong></div></div><p class="small">При досрочном уходе окончательный расчёт меняется; ранние выплаты могут учитываться как аванс.</p><a class="text-link" href="/payments.html#early">Как устроены выплаты ↗</a></div></div>'''
def vip():
    return '''<div class="vip-levels"><div><span>10–14 активных</span><strong>5<small>%</small></strong></div><div><span>15–19 активных</span><strong>7<small>%</small></strong></div><div><span>20–29 активных</span><strong>9<small>%</small></strong></div><div><span>30+ активных</span><strong>10<small>%</small></strong></div></div><p class="small">Процент от подтверждённого заработка активной сети. Уровень пересчитывается по текущему числу активных моделей; ниже 10 VIP-выплаты приостанавливаются.</p>'''
home='''<section class="hero wrap"><div class="hero-copy"><span class="eyebrow">Партнёрская программа для скаутов · 18+</span><h1>Твои знакомства<br>могут приносить<br><em>больше.</em></h1><p class="hero-lead">Стань скаутом SCAUTDOM. Находи девушек для работы вебкам-моделями на Chaturbate — платформе для взрослых. Мы берём на себя отбор, обучение и запуск.</p><div class="actions">'''+button('Узнать, как начать','/scout.html#apply')+'''<a class="text-link" href="#how">Как это работает <span aria-hidden="true">↓</span></a></div><div class="hero-bottom"><span>Твой навык — общение.</span><span>Твоя возможность — новый доход.</span></div></div><figure class="hero-visual"><img src="/assets/scout.svg" alt="Иллюстрация: взрослая девушка работает за ноутбуком в светлом офисе" width="1122" height="1402" fetchpriority="high"><div class="photo-label">Умение знакомить —<br>тоже ценный навык.</div><div class="payout-float"><span class="eyebrow">Вознаграждение скаута</span><strong>$3 000</strong><span>за одобренную модель,<br>завершившую 3 месяца работы</span><a href="/payments.html">Посмотреть условия ↗</a></div><figcaption>Фотоиллюстрация, созданная с помощью ИИ.</figcaption></figure></section><div class="benefit-strip"><div class="wrap"><span>Можно без опыта</span><span>Обучение модели — на нас</span><span>До $3 000 за модель</span><span>VIP до 10% от сети</span></div></div>
<section class="section wrap" id="opportunity">'''+heading('01 / У тебя уже может быть преимущество','Не начинаешь с нуля.<br>Начинаешь <em>со своего круга.</em>','Скаут замечает интерес человека, умеет объяснить возможность и помогает сделать первый шаг. Посмотри, в чём твоя сильная сторона.')+'''<div class="audience-grid"><article class="audience-card"><span class="card-symbol" aria-hidden="true">↗</span><span class="eyebrow">Знакомства</span><h3>Ты легко находишь<br>общий язык</h3><p>Подруги, знакомые, взрослое университетское окружение. Доверие помогает начать содержательный разговор.</p></article><article class="audience-card"><span class="card-symbol" aria-hidden="true">✳</span><span class="eyebrow">Бьюти и творчество</span><h3>Вокруг тебя<br>много девушек</h3><p>Работаешь в салоне, фотографии, макияже или другой сфере, где постоянно знакомишься с людьми.</p></article><article class="audience-card blue-card"><span class="card-symbol" aria-hidden="true">＋</span><span class="eyebrow">Аудитория и рекрутинг</span><h3>Умеешь находить<br>«своих» людей</h3><p>Создаёшь контент или занимаешься подбором. Можешь выстроить свой источник заинтересованных кандидатов.</p></article></div></section>
<section class="section ink" id="how"><div class="wrap">'''+heading('02 / Простая роль. Понятная ценность.','Ты открываешь возможность.<br><em>Мы помогаем её реализовать.</em>','Скауту не нужно вести эфиры, обучать модель или управлять её аккаунтом. Твоя работа — найти подходящего человека и познакомить с командой.')+timeline()+'''<a class="text-link" href="/scout.html">Весь путь скаута — с примерами ↗</a></div></section>
<section class="section wrap" id="income">'''+heading('03 / Твоя экономика','Одно знакомство.<br><em>Три этапа вознаграждения.</em>','За одну одобренную модель — по $1 000 после каждого из первых трёх полных месяцев при выполнении условий. Можно двигаться от первого результата к нескольким моделям.')+calculator()+'''</section>
<section class="section soft"><div class="wrap split"><div><span class="eyebrow">04 / Возможность роста</span><h2>Собирай свою сеть.<br><em>Развивай доход.</em></h2><p>От 10 активных моделей открывается VIP-программа: дополнительный процент от подтверждённого заработка сети.</p>'''+button('Подробнее о VIP','/payments.html#vip','outline')+'''</div><div>'''+vip()+'''</div></div></section>
<section class="section wrap"><div class="split candidate-preview"><div><span class="eyebrow">05 / Кого знакомить с нами</span><h2>Хороший старт<br>важнее <em>готового опыта.</em></h2><p>Мы рассматриваем совершеннолетних девушек, которые хотят освоить вебкам с нуля и готовы к регулярной работе. Важно, чтобы человек понимал предложение и выбирал его сам.</p>'''+button('Разобраться в условиях моделей','/model.html','outline')+'''</div><div class="profile-card"><div class="profile-title"><span class="eyebrow">Портрет кандидата</span><span class="tag">18+</span></div><dl><div><dt>Возраст</dt><dd>Приоритет 18–23 года</dd></div><div><dt>Опыт</dt><dd>Новичок в вебкаме</dd></div><div><dt>Настрой</dt><dd>Учиться и развиваться</dd></div><div><dt>График модели</dt><dd>От 8 часов × 5 дней</dd></div><div><dt>Формат</dt><dd>Эфиры на Chaturbate</dd></div></dl><p class="small">Обучение без отдельной платы. Подготовку рабочего места обсуждаем перед запуском.</p></div></div></section>
<section class="section wrap line-top">'''+heading('06 / Ответы до первого сообщения','Всё, что хочется<br><em>уточнить сначала.</em>')+faqs([
('Кто такой скаут и что именно он делает?','Скаут — партнёр по поиску моделей. Он находит совершеннолетнюю девушку, объясняет работу в вебкаме, уточняет её готовность и с её согласия знакомит с компанией. Обучение, эфиры и сопровождение модели берёт на себя команда.'),
('Мне нужно самому быть моделью или вести эфиры?','Нет. Роль скаута — знакомить подходящих кандидатов с командой. Работа модели и её график — отдельная роль.'),
('Я могу начать без опыта?','Да. Начни с инструкции и понимания условий. На первом обращении расскажи, где собираешься искать людей: личные знакомства, собственная аудитория или опыт в подборе.'),
('За что выплачиваются $3 000?','За одобренную модель, которая выполняет согласованный план и завершает первые три полных месяца работы. Выплаты распределены по $1 000 на месяц. При досрочном уходе действует перерасчёт. <a href="/payments.html#early">Разобрать примеры</a>.'),
('Что говорить девушке о работе?','Сразу объясни, что речь о вебкаме на Chaturbate — платформе для взрослых. Затем расскажи об обучении, поддержке, графике и доле дохода. На странице <a href="/model.html">«Кого искать»</a> всё собрано для такого разговора.'),
('С чего начинается наше общение?','С твоего источника кандидатов и плана. Короткая анкета подготовит сообщение в Telegram, чтобы команда сразу понимала твою ситуацию. Отправишь его после проверки текста.')])+'''</section>'''+cta()
write('index.html','SCAUTDOM — стань скаутом и развивай свой доход','Находи взрослых моделей для Chaturbate. До $3 000 за модель по условиям программы, обучение и запуск на стороне команды, VIP от активной сети.',home)

# Both flows prepare an explicit Telegram draft. No application backend is implied.
def quiz(mode='scout'):
    if mode=='scout':
        first='''<legend tabindex="-1">С чего начнётся твой поиск?</legend><p class="muted">Выбери то, что ближе тебе сейчас.</p><div class="choices"><label class="choice"><input type="radio" name="source" value="network" required><span><strong>Личные знакомства</strong><small>Есть подруги и взрослое окружение</small></span></label><label class="choice"><input type="radio" name="source" value="audience" required><span><strong>Своя аудитория</strong><small>Веду страницу или сообщество</small></span></label><label class="choice"><input type="radio" name="source" value="recruiting" required><span><strong>Навык подбора</strong><small>Умею находить и заинтересовывать людей</small></span></label><label class="choice"><input type="radio" name="source" value="exploring" required><span><strong>Хочу выстроить свой путь</strong><small>Изучаю возможность и готовлю план</small></span></label></div>'''
        second='''<legend tabindex="-1">Теперь — о твоём первом шаге</legend><p class="route-tip" data-route-tip></p><label class="field"><span>Как к тебе обращаться?</span><input name="name" autocomplete="given-name" maxlength="50" required placeholder="Имя или псевдоним"></label><label class="field"><span>Где и как планируешь искать моделей?</span><textarea name="plan" minlength="20" maxlength="400" required rows="3" placeholder="Например: я визажист, хочу начать с личных знакомых, которым интересна эта сфера."></textarea></label><label class="field"><span>Что хочешь уточнить? <small>Необязательно</small></span><textarea name="question" maxlength="240" rows="2" placeholder="Один главный вопрос к команде"></textarea></label><label class="check"><input type="checkbox" name="age" value="adult" required><span>Мне исполнилось 18 лет.</span></label><label class="check"><input type="checkbox" name="terms" value="yes" required><span>Понимаю формат вебкам 18+ на Chaturbate, буду знакомить кандидатов с ним заранее и передавать данные с их согласия. Изучил(а) <a href="/payments.html" target="_blank" rel="noopener">условия выплат</a>, включая три полных месяца и перерасчёт.</span></label>'''
        intro='''<span class="eyebrow">Твой следующий шаг · около 2 минут</span><h2>Давай познакомимся.<br><em>С твоего плана.</em></h2><p>Расскажи, какой у тебя круг общения и как хочешь начать. Команда получит конкретное обращение и сможет перейти к делу.</p><div class="application-note"><strong>Что будет дальше</strong><p>Ты проверишь готовый текст и отправишь его в Telegram. Затем обсудишь с командой свой старт и вопросы по программе.</p></div>'''
    else:
        first='''<legend tabindex="-1">Расскажи немного о себе</legend><label class="field"><span>Возраст</span><select name="age" required><option value="">Выбери ответ</option><option value="adult">18–23 года</option><option value="older">24 года или больше</option><option value="minor">Меньше 18 лет</option></select></label><label class="field"><span>Опыт работы в вебкаме</span><select name="experience" required><option value="">Выбери ответ</option><option value="new">Начинаю с нуля</option><option value="experienced">Есть опыт</option></select></label><label class="field"><span>Страна проживания</span><input name="country" autocomplete="country-name" maxlength="70" required></label>'''
        second='''<legend tabindex="-1">Твоя готовность к старту</legend><label class="field"><span>Как к тебе обращаться?</span><input name="name" autocomplete="given-name" maxlength="50" required></label><label class="field"><span>График: от 8 часов в день, 5 дней в неделю</span><select name="schedule" required><option value="">Выбери ответ</option><option value="ready">Подходит</option><option value="discuss">Хочу обсудить</option><option value="no">Не подходит</option></select></label><label class="field"><span>Рабочее место</span><select name="equipment" required><option value="">Выбери ответ</option><option value="ready">Компьютер, камера и интернет готовы</option><option value="partial">Нужно кое-что подготовить</option><option value="none">Пока нет оборудования</option></select></label><label class="field"><span>Когда хочешь начать?</span><select name="timing" required><option value="">Выбери ответ</option><option value="soon">В ближайшие 2 недели</option><option value="month">В течение месяца</option><option value="exploring">Пока изучаю</option></select></label><label class="field"><span>Твой вопрос <small>Необязательно</small></span><textarea name="question" maxlength="240" rows="2"></textarea></label><label class="check"><input type="checkbox" name="terms" value="yes" required><span>Понимаю, что это вебкам на Chaturbate для взрослых. Хочу обсудить работу по собственной инициативе. Изучила график, базовую долю 50% и особенности публичных эфиров.</span></label>'''
        intro='''<span class="eyebrow">Для самостоятельного обращения модели</span><h2>Хочешь обсудить<br><em>свой старт?</em></h2><p>Если читаешь эту страницу для себя, расскажи о готовности к работе. Участие только с 18 лет.</p>'''
    return f'''<section class="section application" id="apply"><div class="wrap application-grid"><div>{intro}<p class="small">Ответы обрабатываются на этой странице. Команда увидит их после отправки сообщения тобой. <a href="/privacy.html">Подробнее</a>.</p></div><div><noscript><div class="quiz"><p>Для анкеты нужен JavaScript. Если тебе есть 18 лет, напиши в Telegram свою роль, понимание вебкам-формата и план начала работы.</p><a href="https://t.me/scauttdom" rel="noopener noreferrer">Открыть @scauttdom ↗</a></div></noscript><form class="quiz" data-quiz="{mode}" hidden><div class="quiz-top"><p data-counter aria-live="polite">01 / Твой старт</p><div class="progress" aria-hidden="true"><i></i><i></i><i></i></div></div><fieldset data-step>{first}</fieldset><fieldset data-step hidden disabled>{second}</fieldset><fieldset data-step hidden disabled><legend tabindex="-1">Можно переходить к знакомству.</legend><p class="route-tip" data-review-status></p><label class="field"><span>Текст для команды — проверь перед отправкой</span><textarea class="review-message" data-message readonly rows="10"></textarea></label><div class="actions"><a class="button primary" data-telegram href="https://t.me/scauttdom" target="_blank" rel="noopener noreferrer">Открыть Telegram ↗</a><button type="button" class="button outline" data-copy>Скопировать</button></div><p class="small">В Telegram нажми «Отправить». Если текст не подставился, скопируй его и вставь в чат <strong>@scauttdom</strong>.</p><p class="small" data-copy-status role="status"></p><button type="button" class="back" data-edit>← Изменить ответы</button></fieldset><p class="form-error" data-error role="alert"></p><div class="quiz-actions" data-controls><button type="button" class="back" data-back hidden>← Назад</button><button type="submit" class="button primary" data-next>Мой следующий шаг ↗</button></div></form></div></div></section>'''
scout='''<section class="page-hero wrap"><span class="eyebrow">Путь скаута / SCAUTDOM</span><h1>Умеешь находить людей?<br><em>Давай начнём с этого.</em></h1><div class="page-intro"><p>Твоя роль — познакомить подходящую совершеннолетнюю девушку с возможностью работы вебкам-моделью на Chaturbate. Подробный путь от первого разговора до передачи кандидата — ниже.</p>'''+button('Обсудить мой старт','#apply')+'''</div></section><section class="wrap section line-top">'''+heading('01 / Суть сотрудничества','У каждого — своя<br><em>сильная сторона.</em>')+timeline()+'''</section><section class="section soft"><div class="wrap split"><div><span class="eyebrow">02 / Начни с подходящего круга</span><h2>Ищи интерес.<br><em>Не просто контакт.</em></h2><p>Хороший кандидат понимает сферу, хочет освоить работу и готов обсуждать конкретный график. Несколько таких разговоров полезнее десятков случайных номеров.</p><a class="text-link" href="/model.html">Портрет модели и все условия ↗</a></div><div class="editorial-list"><article><span>01</span><div><h3>Личные знакомства</h3><p>Совершеннолетние подруги, знакомые и их рекомендации. Предложи прочитать условия и оставь человеку пространство для решения.</p></div></article><article><span>02</span><div><h3>Твой профессиональный круг</h3><p>Бьюти, фотография, творчество и другие сферы общения. Уместный личный разговор — когда человек открыт к такому предложению.</p></div></article><article><span>03</span><div><h3>Твоя взрослая аудитория</h3><p>Понятный контент о самой работе скаута и условиях. Заинтересованный человек заранее знает, с каким предложением приходит.</p></div></article></div></div></section>
<section class="section wrap"><div class="split"><div><span class="eyebrow">03 / Первый разговор</span><h2>Скажи просто.<br><em>И по существу.</em></h2><p>Сначала назови сферу. Затем покажи, что человек получает: обучение, сопровождение и возможность развиваться. Так интерес появляется к реальной работе.</p><p class="small">Пример для личного разговора со взрослой знакомой. Адаптируй под отношения и не отправляй массово.</p></div><div class="message-card"><span class="eyebrow">Пример первого сообщения</span><blockquote id="outreach-text">Привет! Я изучаю партнёрскую программу SCAUTDOM: команда обучает девушек работе вебкам-моделями на Chaturbate, платформе для взрослых. Есть обучение с нуля и помощь с запуском. Если сама рассматриваешь эту сферу, могу отправить условия — посмотришь, подходит ли тебе формат и график.</blockquote><button class="text-link" type="button" data-copy-target="outreach-text">Скопировать пример ↗</button><p class="small" data-template-status role="status"></p></div></div></section>
<section class="section ink"><div class="wrap">'''+heading('04 / О чём поговорить','Шесть вопросов,<br><em>которые помогают делу.</em>','Заранее разберись в ответах. Тогда при знакомстве с командой можно обсуждать запуск, а не начинать объяснение заново.')+'''<div class="question-grid"><article><span>01</span><h3>Ей уже есть 18?</h3><p>Приоритет 18–23 года. Другие взрослые кандидаты рассматриваются индивидуально.</p></article><article><span>02</span><h3>Понимает формат?</h3><p>Вебкам на Chaturbate, платформе с эротическим контентом. Решение должно быть её собственным.</p></article><article><span>03</span><h3>Готова учиться?</h3><p>Приоритет новичкам, которые хотят освоить работу и настроены на долгий срок.</p></article><article><span>04</span><h3>Подходит график?</h3><p>Для модели — от 8 часов в день, 5 дней в неделю. Уточни готовность до передачи.</p></article><article><span>05</span><h3>Есть рабочее место?</h3><p>Компьютер, камера, отдельное место и интернет от 20 Мбит/с в обе стороны. Недостающую технику обсуждаем.</p></article><article><span>06</span><h3>Где она находится?</h3><p>Уточни страну и город. Возможность запуска и детали компания согласует с кандидатом.</p></article></div></div></section>
<section class="section wrap"><div class="split"><div><span class="eyebrow">05 / Передача кандидата</span><h2>Подготовь знакомство.<br><em>Мы подхватим дальше.</em></h2><p>После согласия девушки передай команде её имя, полный возраст, страну и город, обычные фотографии с её разрешения и краткие ответы на вопросы выше.</p><p>Компания проводит итоговый отбор, проверяет совершеннолетие напрямую, обучает и фиксирует дату запуска. Фото документов скаут не собирает.</p></div><div class="profile-card"><span class="eyebrow">Удобная структура</span><ul class="simple-list"><li>Имя и полный возраст</li><li>Страна и город</li><li>Опыт, график и оборудование</li><li>Когда готова начать</li><li>Понимание формата и согласие на знакомство</li><li>Вопросы, которые хочет обсудить</li></ul><p class="small">Здесь на сайте заполняется анкета скаута. Данные кандидата передаются отдельно после согласования с командой.</p></div></div></section><section class="section wrap line-top">'''+heading('06 / Договорённости','Понятные роли<br><em>помогают сотрудничать.</em>')+faqs([
('Что происходит после передачи модели?','Рабочее общение с моделью ведёт компания. По условиям программы скаут после передачи не обсуждает с ней рабочие аккаунты, контент, график, доход и внутренние процессы. Это позволяет закрепить ответственность за сопровождение за одной командой.'),
('Как закрепляется кандидат и учитываются выплаты?','Компания фиксирует кандидата, одобрение, дату запуска, расчётные месяцы и активность. Учёт и подтверждение начислений идут вручную, через Telegram; личного кабинета сейчас нет.'),
('Если результат модели ниже ожидаемого?','Сам по себе доход ниже прогноза не отменяет выплату скауту, если одобренная модель выполняет согласованный план, завершает три месяца, а скаут соблюдает правила.'),
('Какие правила нужно учитывать?','Только совершеннолетние кандидаты, правдивые сведения и фотографии, предварительное понимание формата и согласие на передачу информации. Повторная передача уже известного кандидата, вымышленные данные и вмешательство в работу могут привести к пересмотру выплат. При обоснованных признаках мошенничества начисления могут приостановить на время проверки; подтверждённое нарушение может привести к аннулированию связанных выплат.')])+'''</section>'''+quiz()
write('scout.html','Как стать скаутом SCAUTDOM — от знакомства до вознаграждения','Пошаговый путь скаута: где искать взрослых моделей, что объяснять, как передавать кандидата и начать сотрудничество с SCAUTDOM.',scout)

model='''<section class="page-hero wrap"><span class="eyebrow">Материал для скаута / Условия моделей</span><h1>Когда предложение понятно,<br><em>интерес становится осознанным.</em></h1><div class="page-intro"><p>Всё, что стоит объяснить девушке до знакомства с командой: работа вебкам-моделью на Chaturbate, обучение, поддержка, рабочий график и доход.</p>'''+button('Посмотреть портрет кандидата','#candidate')+'''</div></section><section class="section wrap line-top" id="candidate"><div class="split"><div><span class="eyebrow">01 / Кому подходит</span><h2>Начало карьеры.<br><em>С поддержкой команды.</em></h2><p>Ищем взрослых девушек, которым интересна сфера вебкам и которые хотят освоить её с нуля. Уверенность перед камерой может прийти с практикой — важнее желание учиться и регулярная работа.</p><p>Chaturbate — платформа прямых эфиров для взрослых, в том числе с эротическим контентом. Личный формат и границы модель обсуждает с командой до начала.</p></div><div class="profile-card"><span class="eyebrow">Основные ориентиры</span><dl><div><dt>Возраст</dt><dd>Приоритет 18–23</dd></div><div><dt>Опыт</dt><dd>Приоритет новичкам</dd></div><div><dt>График</dt><dd>8+ часов, 5 дней в неделю</dd></div><div><dt>Настрой</dt><dd>Долгосрочное развитие</dd></div><div><dt>Решение</dt><dd>Собственный интерес к сфере</dd></div></dl><p class="small">Компания принимает окончательное решение после знакомства. Кандидаты старше 23 лет обсуждаются индивидуально.</p></div></div></section>
<section class="section soft"><div class="wrap">'''+heading('02 / Что получает модель','Не нужно заранее<br><em>уметь всё.</em>','Обучение без отдельной платы. После одобрения команда помогает последовательно подготовиться к работе и развивать аккаунт.')+'''<div class="audience-grid"><article class="audience-card"><span class="card-symbol">01</span><h3>Подготовка<br>и обучение</h3><p>Разбор формата, настройка техники, подготовка к работе в кадре и общению с аудиторией.</p></article><article class="audience-card"><span class="card-symbol">02</span><h3>Помощь<br>с запуском</h3><p>Регистрация, проверка данных, рабочий график и первые шаги в проведении трансляций.</p></article><article class="audience-card blue-card"><span class="card-symbol">03</span><h3>Сопровождение<br>и развитие</h3><p>Рекомендации по аккаунту, продвижению, взаимодействию с аудиторией и улучшению результатов.</p></article></div></div></section>
<section class="section wrap" id="income"><div class="split"><div><span class="eyebrow">03 / Как объяснить доход</span><h2>Понятная доля.<br><em>Возможность роста.</em></h2><p>Базовая доля модели — 50%. За сильные результаты доля за расчётный месяц может повышаться по VIP-программе.</p><p>Заработок зависит от фактического результата эфиров. Пример расчёта: если согласованная база для распределения составляет $3 000, при доле 50% модель получает $1 500. Это арифметический пример, не обещание месячного дохода.</p><p class="small">Точную базу расчёта, удержания, способ и даты выплат нужно согласовать с командой до старта.</p></div><div class="model-share"><span class="eyebrow">Базовая доля модели</span><strong>50<span>%</span></strong><p>Обучение и сопровождение —<br>часть работы команды.</p></div></div><div class="table-wrap"><table><caption>VIP-программа моделей</caption><thead><tr><th>Результат за месяц</th><th>Доля модели</th><th>Условия</th></tr></thead><tbody><tr><td>$5 000</td><td>52%</td><td>Высокая активность, график около 10 часов в сутки</td></tr><tr><td>$8 000</td><td>55%</td><td>Стабильный результат и высокая вовлечённость</td></tr><tr><td>$20 000</td><td>60%</td><td>Выполнение рабочего плана и сильный результат</td></tr></tbody></table></div><p class="small">Повышение рассматривается компанией за конкретный месяц. Значение «результат за месяц» и расчётную базу необходимо подтвердить до начала работы; пороги не означают гарантированный доход на руки.</p></section>
<section class="section ink"><div class="wrap split"><div><span class="eyebrow">04 / Рабочее место</span><h2>Подготовить основу.<br><em>Затем запускаться.</em></h2><p>Для модели предусмотрен график от 8 часов в день, 5 дней в неделю. Регулярность нужна для работы над аккаунтом и аудиторией.</p><p>Если часть техники ещё нужно подготовить, обсудите это с командой после предварительного рассмотрения.</p></div><div class="editorial-list"><article><span>01</span><div><h3>Компьютер и камера</h3><p>Стабильная работа при длительных эфирах. В условиях программы указаны Logitech C920 или C920s как варианты камеры.</p></div></article><article><span>02</span><div><h3>Интернет в обе стороны</h3><p>От 20 Мбит/с на приём и на отдачу, устойчивое соединение без постоянных обрывов.</p></div></article><article><span>03</span><div><h3>Место для эфиров</h3><p>Тихое отдельное пространство, свет и возможность спокойно соблюдать согласованный график.</p></div></article></div></div></section>
<section class="section wrap">'''+heading('05 / От знакомства к работе','Сначала разговор.<br><em>Потом — план запуска.</em>')+'''<ol class="timeline"><li><span class="step-no">01</span><div><h3>Знакомство и отбор</h3><p>Команда изучает базовую информацию и обсуждает готовность кандидата.</p></div></li><li><span class="step-no">02</span><div><h3>Условия и проверка</h3><p>Напрямую с моделью: формат, совершеннолетие, регистрация, выплаты и рабочие договорённости.</p></div></li><li><span class="step-no">03</span><div><h3>Подготовка и обучение</h3><p>Оборудование, рабочее место, обучение и согласование графика.</p></div></li><li><span class="step-no">04</span><div><h3>Старт и сопровождение</h3><p>Фиксируется дата начала. Команда помогает с запуском и дальнейшим развитием.</p></div></li></ol></section>
<section class="section wrap line-top">'''+heading('06 / Ответы для разговора','Полезно понимать<br><em>до решения.</em>')+faqs([
('Что можно обещать кандидату?','Условия программы: обучение без отдельной платы, помощь с подготовкой и запуском, базовую долю и возможность её повышения. Не называй пример заработка гарантией. Итоговый отбор и все конкретные договорённости проходят с компанией.'),
('Кто выбирает допустимый формат?','Совершеннолетняя модель сама определяет, подходит ли ей сфера и какой формат для неё допустим. Это обсуждается заранее. Предложение не должно скрывать взрослый характер платформы.'),
('Можно ли гарантировать анонимность?','Полную анонимность обещать нельзя: эфиры могут записываться и распространяться другими людьми. Настройки приватности не устраняют этот риск полностью. Обсуди этот вопрос до начала работы.'),
('Нужны ли документы скауту?','Нет. Скаут передаёт обычную информацию и разрешённые кандидатом фотографии. Проверка личности проводится компанией напрямую с моделью.')])+'''</section>'''+cta()+quiz('model')
write('model.html','Кого искать скауту — условия моделей SCAUTDOM','Материал для скаута: портрет взрослой модели, формат Chaturbate, обучение с нуля, график, оборудование, базовая доля 50% и VIP.',model)

payments='''<section class="page-hero wrap"><span class="eyebrow">Вознаграждение скаута / SCAUTDOM</span><h1>Понимай свой доход.<br><em>Планируй следующий шаг.</em></h1><div class="page-intro"><p>До $3 000 за каждую одобренную модель, завершившую первые три полных месяца работы. От 10 активных моделей — дополнительный VIP-процент.</p>'''+button('Рассчитать пример','#calculator')+'''</div></section><section class="section wrap line-top"><span class="eyebrow">01 / Базовое вознаграждение</span><div class="payment-hero"><strong>$3 000</strong><p>Одна модель.<br>Три полных расчётных месяца.<br>Выполненный рабочий план.</p></div><div class="payment-months"><article><span>После 1-го полного месяца</span><h3>$1 000</h3><p>Начисление после подтверждения рабочего периода.</p></article><article><span>После 2-го полного месяца</span><h3>$1 000</h3><p>Модель продолжает работу по согласованному плану.</p></article><article><span>После 3-го полного месяца</span><h3>$1 000</h3><p>Завершён обязательный период. Полное вознаграждение — $3 000.</p></article></div><p class="small">Даты расчётных месяцев фиксируются компанией после запуска. Передача контакта и предварительное одобрение сами по себе не создают выплату. Досрочный уход влияет на окончательный расчёт — примеры ниже.</p></section>
<section class="section soft" id="calculator"><div class="wrap">'''+heading('02 / Посмотри на свою цель','От первой модели<br><em>к нескольким результатам.</em>')+calculator()+'''</div></section>
<section class="section wrap" id="early">'''+heading('03 / Если планы изменились','Как считается<br><em>досрочный уход.</em>','Полное вознаграждение связано с завершением всех трёх месяцев. Сохраняем этот пункт рядом с расчётом, чтобы ожидания совпадали с условиями.')+'''<div class="table-wrap"><table><thead><tr><th>Ситуация</th><th>Как меняется расчёт</th></tr></thead><tbody><tr><td>Ушла в течение 1-го месяца</td><td>Полный месяц не завершён. Вознаграждение не начисляется.</td></tr><tr><td>Ушла в течение 2-го месяца</td><td>Ранее перечисленная сумма учитывается как аванс и засчитывается при выплате за следующую одобренную модель скаута.</td></tr><tr><td>Ушла в течение 3-го месяца</td><td>Третий платёж не начисляется. Обязательный период не выполнен; окончательный расчёт пересматривается.</td></tr><tr><td>Завершила все 3 месяца</td><td>При выполнении рабочего плана полное вознаграждение составляет $3 000.</td></tr></tbody></table></div><div class="note"><strong>Низкий доход модели сам по себе не отменяет выплату.</strong><p>Если компания одобрила модель, она выполнила согласованный план и завершила три месяца, риск ошибки отбора относится к компании — при правдивых данных и соблюдении скаутом условий программы.</p></div></section>
<section class="section ink" id="vip"><div class="wrap">'''+heading('04 / VIP-программа','Развивай активную сеть.<br><em>Получай дополнительный процент.</em>','Процент считается от подтверждённого заработка моделей твоей активной сети. Это отдельная возможность роста после достижения 10 активных моделей.')+vip()+'''<div class="vip-example"><span class="eyebrow">Арифметический пример</span><h3>10 активных моделей × $3 000 подтверждённого заработка × 5% = $1 500</h3><p>Пример VIP-начисления за расчётный период. Здесь $3 000 — условная база заработка одной модели, а не обещанный результат. Конкретная база расчёта подтверждается компанией.</p></div></div></section>
<section class="section wrap"><div class="split"><div><span class="eyebrow">05 / Как определяется уровень</span><h2>Важна работающая сеть.<br><em>Не число контактов.</em></h2><p>Активная модель одобрена компанией, начала работу, выполняет согласованный график и продолжает сотрудничество. Статус подтверждается по фактической работе.</p><p>Ушедшие и временно неактивные модели не учитываются до восстановления активности.</p></div><div class="editorial-list"><article><span>10 → 9</span><div><h3>VIP приостанавливается</h3><p>Ниже минимального порога в 10 активных моделей.</p></div></article><article><span>14 → 15</span><div><h3>Процент растёт до 7%</h3><p>После подтверждения нового уровня активной сети.</p></div></article><article><span>20 → 18</span><div><h3>Новый уровень — 7%</h3><p>Текущий размер сети соответствует диапазону 15–19.</p></div></article></div></div></section>
<section class="section wrap line-top">'''+heading('06 / Учёт и договорённости','Что уточнить<br><em>перед первым кандидатом.</em>')+faqs([
('Как фиксируются модели и расчётные периоды?','Учёт ведётся компанией вручную. Через Telegram подтверждаются передача кандидата, одобрение, дата начала, активность и начисления. До передачи кандидата согласуйте порядок подтверждений и закрепления модели за скаутом.'),
('Когда и каким способом приходят выплаты?','На сайте указан порядок начисления после полных расчётных месяцев. Конкретные даты перевода, валюта, способ и возможные комиссии согласовываются с компанией в Telegram. Не путай завершение месяца с моментом поступления денег.'),
('Почему выплата может попасть на проверку?','При обоснованных признаках мошенничества: вымышленных кандидатах, дубликатах, ложных данных или фотографиях, а также вмешательстве скаута в работу модели. На период проверки начисления могут приостановить. Подтверждённое нарушение может привести к аннулированию связанных выплат и VIP-процента.'),
('Что означает правило рабочего общения?','После передачи модели рабочие вопросы — аккаунты, контент, график, заработок и внутренние процессы — ведёт компания. Намеренное влияние скаута на уход модели или нарушение этого правила может привести к аннулированию связанных выплат.')])+'''</section>'''+cta()
write('payments.html','Выплаты скаутам SCAUTDOM — $3 000 за модель и VIP','Вознаграждение скаута: три платежа по $1 000, условия полных месяцев, досрочный уход и VIP 5–10% от подтверждённого заработка активной сети.',payments)
privacy='''<section class="page-hero wrap"><span class="eyebrow">SCAUTDOM / О данных</span><h1>Твоё обращение.<br><em>Под твоим контролем.</em></h1></section><section class="section wrap prose"><h2>Что делает анкета</h2><p>Анкета подготавливает текст сообщения на твоём устройстве. Ответы не записываются в cookies, localStorage или sessionStorage и не отправляются в базу заявок сайта. После обновления страницы ответы могут исчезнуть.</p><h2>Как команда получает обращение</h2><p>Кнопка Telegram открывает чат @scauttdom с подготовленным текстом. Само открытие чата не означает отправку или получение заявки. Проверь текст и нажми «Отправить» в Telegram. Если текст не подставился, можно скопировать его вручную.</p><p>При переходе в Telegram текст передаётся в адресе ссылки сервису Telegram для создания черновика. Не вписывай в анкету паспортные данные, документы, сведения о третьих лицах и другую чувствительную информацию.</p><h2>Что остаётся в сообщении</h2><p>Выбранная роль, ответы анкеты, случайный код обращения и, если они были в ссылке, метки рекламного источника. Метки нужны, чтобы понять, откуда пришёл человек. Не размещайте в них персональные данные. Метки передаются по внутренним ссылкам, но не сохраняются в браузерном хранилище.</p><h2>Технические события и аналитика</h2><p>Страница создаёт технические события начала анкеты, подготовки текста и перехода в Telegram. В них нет ответов анкеты, имени и свободного текста. Отдельный сборщик отчётов сейчас не подключён. Рекламный Meta Pixel не загружается. Хостинг и Telegram могут обрабатывать технические данные по своим условиям.</p><h2>Данные кандидатов</h2><p>Скаут передаёт сведения взрослого кандидата только с его разрешения. Проверка личности проводится компанией напрямую; документы не запрашиваются через анкету сайта.</p><h2>Вопросы о переданном сообщении</h2><p>По вопросам исправления или удаления информации, отправленной команде, обращайся в тот же <a href="https://t.me/scauttdom" rel="noopener noreferrer">чат @scauttdom</a>. Сведения о стороне договора и порядке дальнейшей обработки данных необходимо согласовать с командой перед передачей документов и началом работы.</p></section>'''
write('privacy.html','Конфиденциальность — SCAUTDOM','Как анкета SCAUTDOM подготавливает сообщение, что передаётся в Telegram и как используются метки источника.',privacy)
write('404.html','Страница не найдена — SCAUTDOM','Вернуться к партнёрской программе SCAUTDOM.','<section class="page-hero wrap"><span class="eyebrow">404</span><h1>Нужная возможность<br><em>на другой странице.</em></h1><div class="actions">'+button('На главную','/')+button('Как стать скаутом','/scout.html','outline')+'</div></section>')
(R/'sitemap.xml').write_text('<?xml version="1.0" encoding="UTF-8"?><urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">'+''.join(f'<url><loc>https://www.scautdom.com{p}</loc></url>' for p in ['/','/scout.html','/model.html','/payments.html','/privacy.html'])+'</urlset>')
(R/'robots.txt').write_text('User-agent: *\nAllow: /\nSitemap: https://www.scautdom.com/sitemap.xml\n')
print('Generated six HTML routes and search metadata.')
